## 标量

In [1]:
import torch

x = torch.tensor([3])
y = torch.tensor([2])
x + y, x * y, x / y, x ** y

(tensor([5]), tensor([6]), tensor([1.5000]), tensor([9]))

## 向量

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
len(x)

4

In [5]:
x.shape

torch.Size([4])

## 矩阵

In [20]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A[2,3]

tensor(11)

In [9]:
A[2]

tensor([ 8,  9, 10, 11])

In [11]:
A[:,3]

tensor([ 3,  7, 11, 15, 19])

In [12]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [13]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [18]:
C = B.T
C == B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [17]:
id(B), id(C)

(140378192045544, 140378192067824)

## 张量

In [24]:
X = torch.arange(24).reshape((2,3,4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质

In [25]:
A = torch.arange(20, dtype=torch.float32).reshape((5,4))
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [26]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [28]:
# 标量和张量运算
a = 2
X = torch.arange(24).reshape((2,3,4))
X, a + X, a * X

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

## 降维

In [29]:
# .sum()
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [30]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [33]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [34]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [35]:
A.sum(axis=[0, 1])

tensor(190.)

In [36]:
# .mean()
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [37]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [38]:
# 非降维求和
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [39]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [40]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [41]:
# 累积求和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积

In [42]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [43]:
torch.sum(x * y)

tensor(6.)

## 矩阵-向量积

In [44]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵-矩阵乘法

In [47]:
B = torch.arange(12, dtype=torch.float32).reshape((4, 3))
A.shape, B.shape, torch.mm(A, B)

(torch.Size([5, 4]),
 torch.Size([4, 3]),
 tensor([[ 42.,  48.,  54.],
         [114., 136., 158.],
         [186., 224., 262.],
         [258., 312., 366.],
         [330., 400., 470.]]))

## 范数

In [48]:
u = torch.tensor([3.0, 4.0])
torch.norm(u)  # L2范数

tensor(5.)

In [49]:
torch.abs(u).sum()  # L1范数

tensor(7.)

In [52]:
torch.norm(torch.ones((4,9)))

tensor(6.)

## 练习

In [64]:
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]))

In [56]:
# 转置
A.T.T == A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [63]:
(A[:4, :3] + B).T == A[:4, :3].T + B.T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [68]:
C = torch.rand((3,3))
C

tensor([[0.2217, 0.2249, 0.1626],
        [0.8817, 0.4374, 0.4518],
        [0.0299, 0.2204, 0.9758]])

In [71]:
C + C.T  # 对称

tensor([[0.4433, 1.1067, 0.1925],
        [1.1067, 0.8747, 0.6722],
        [0.1925, 0.6722, 1.9515]])

In [73]:
# len
X.shape, len(X)

(torch.Size([2, 3, 4]), 2)

In [74]:
# mean
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [75]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [76]:
A / A.sum(axis=1)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [77]:
A / A.sum(axis=1, keepdim=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [79]:
A.sum(axis=1, keepdim=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [80]:
# 不同轴降维
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [83]:
X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [84]:
X.sum(axis=0, keepdim=True).shape, X.sum(axis=1, keepdim=True).shape, X.sum(axis=2, keepdim=True).shape

(torch.Size([1, 3, 4]), torch.Size([2, 1, 4]), torch.Size([2, 3, 1]))

In [88]:
linalg.norm(X)

NameError: name 'linalg' is not defined